### ISSUE TITLE
static url to api gateway

### ISSUE THREAD

**Issue by sebastian-minatti** [microservices-practical/microservices-v10#1]
https://github.com/microservices-practical/microservices-v10/blob/2397a423fa0cbb2dcd111a05963aa5b625cbf71f/gamification/src/main/resources/application.properties#L19

Hi, the architecture described on page 253, show gamification service asking for gateway url service,to service registry, I don't see that part of the logic here, Am I wrong ? 
Aside from that just want you to let you know the book is awesome and I a really enjoy it and I have learned a lot.

**Comment by mechero** [comment]
Hi, the change is just the port number so it's hard to spot it. The port `8000` points to the api-gateway, so basically the property could also have been renamed to `gatewayHost` or similar. Is that answering your question?

Thanks for the feedback, I'm glad you're enjoying the book! I'd appreciate if you can leave a review on [Amazon](https://www.amazon.com/Learn-Microservices-Spring-Boot-Practical/dp/1484231643) or [Goodreads](https://www.goodreads.com/book/show/36748156-learn-microservices-with-spring-boot?from_search=true) 😄.

**Comment by sebastian-minatti** [comment]
Hi, exactly that point directly to the api gateway, What happens if we want to scale out the api-gateway with more instance ?  gamification will continue pointing to `http://localhost:8000/api` I was thinking that gamification will talk with service registry asking for gateway instance and this one will return the url to the instance in this case `http://localhost:8000/api` .

Thanks in advance for your answer.

**Comment by mechero** [comment]
🤔OK, I see your point now... Yes, indeed that should be updated to `http://gateway/api` when using the service-registry as depicted in that diagram. If it was not being used, then the note from page 214 (Edge Services) would apply in that situation.

Excellent catch! I'll update it in the second edition of the book, thanks!

**Comment by sebastian-minatti** [comment]
u welcome ! thanks to you !
